import { Cloud, Lock, ServerCog } from "lucide-react";
import { Card } from "../components/ui/Card";
import { PageHeader } from "../components/ui/PageHeader";
import { KeyValue } from "../components/ui/States";
import { useHealth } from "../hooks/useSystemStatus";
import { HonestyPanel } from "./Evaluation";

/** S17 About & honesty (PRD FR-1442, DEC-07): what SpecID is, how it is deployed, what the
 * numbers mean (the same honesty text as S11), versions and licences. */
export function About() {
  const health = useHealth();
  const h = health.data as Record<string, unknown> | undefined;
  return (
    <section className="max-w-5xl">
      <PageHeader
        title="About SpecID"
        purpose="A governed national material registry for CPSEs: one national code per real item, decided by engineering rules, approved by people, consented by every CPSE involved."
      />
      <div className="grid gap-5 md:grid-cols-2">
        <Card title="Two ways to run it" hint="The same code runs in both.">
          <div className="space-y-3 text-body">
            <p className="flex gap-2">
              <Cloud size={18} className="mt-0.5 shrink-0 text-auto-fg" aria-hidden="true" />
              <span>
                <strong>Cloud demo</strong> (this link): synthetic data only; the AI reader and
                meaning search may use a hosted model.
              </span>
            </p>
            <p className="flex gap-2">
              <Lock size={18} className="mt-0.5 shrink-0 text-eq-fg" aria-hidden="true" />
              <span>
                <strong>On-premise, air-gapped</strong> (for CPSEs): runs on the CPSE's own servers
                with local models, on a network with no route to the internet; a live counter shows
                blocked outbound attempts. No CPSE data leaves the building.
              </span>
            </p>
            <p className="flex gap-2">
              <ServerCog size={18} className="mt-0.5 shrink-0 text-muted" aria-hidden="true" />
              <span>
                AI reads and proposes; engineering rules decide; people approve. No model can
                override a veto.
              </span>
            </p>
          </div>
        </Card>
        <Card title="Versions">
          <KeyValue k="App" v={String(h?.version ?? "–")} />
          <KeyValue
            k="Commit"
            v={<span className="font-mono">{String(h?.git_commit ?? "–")}</span>}
          />
          <KeyValue
            k="Templates"
            v={
              h?.templates
                ? Object.entries(h.templates as Record<string, number>)
                    .map(([k, v]) => `${k} v${v}`)
                    .join(", ")
                : "–"
            }
          />
          <KeyValue k="Consent" v={String(h?.consent_mode ?? "–")} />
          <KeyValue k="AI provider" v={String(h?.ai_provider ?? "–")} />
          <KeyValue k="Category classifier" v={h?.classifier ? "on (in the app)" : "off"} />
          <p className="mt-3 text-micro text-muted">
            Licences: Inter and JetBrains Mono fonts (SIL OFL), lucide icons (ISC), all bundled.
            Synthetic data generated by SpecID; no real CPSE data.
          </p>
        </Card>
      </div>
      <div className="mt-5">
        <HonestyPanel />
      </div>
    </section>
  );
}
